### ISSUE TITLE
selectFeatures draws on world map even if crs = NA (for mode = "click" only)

### ISSUE THREAD

**Issue by tim-salabim** [r-spatial/mapedit#110]
When using `selectFeatures` with sf features with no crs (i.e. NA) only `mode = "draw"` renders the features correctly without a background map. `mode = "click"` tries to plot things on a world map in web mercator. Should behave as `mode = "draw"`

```r
library(mapedit)
library(mapview)
library(leaflet)
library(sf)

fran = st_set_crs(franconia, NA)

## as expected
selectFeatures(fran, mode = "draw")

## drawing on world map - not what should happen
selectFeatures(fran)
```

**Comment by timelyportfolio** [comment]
@tim-salabim I think the only difference is in [lines](https://github.com/r-spatial/mapedit/blob/master/R/select.R#L72-L80) for `"click"` and lno extent in [line](https://github.com/r-spatial/mapedit/blob/master/R/select.R#L107) for `"draw"`.  If I understand correctly, you prefer `"draw"`, which would mean we remove lines 72-80.  Is this correct?

**Comment by tim-salabim** [comment]
I'll look into this soon. We simply need to adhere to the crs of the data, should be an easy fix

**Comment by tim-salabim** [comment]
OK, this is fixed and merged in master

**Comment by timelyportfolio** [comment]
@tim-salabim thanks!  do we also need the change here https://github.com/r-spatial/mapedit/blob/8328411a45513f788dc25e6b4214df53363d6494/R/select.R#L107?

**Comment by tim-salabim** [comment]
@timelyportfolio no, the `mapview` call will automatically set up the map according to the projection of `x`.

**Comment by timelyportfolio** [comment]
@tim-salabim after `rhub::check_for_cran` I discovered this uses unexported `mapview:::initMap`.  I added a copy in `mapedit` similar to other unexported.  Is this ok with you?  Will you verify that this copy works on your side?

This was the only issue from `rhub::check_for_cran()`.  Did you see anything on `winbuilder`?

Thanks!

**Comment by tim-salabim** [comment]
@timelyportfolio good catch! Sorry for the oversight... I just had a closer look at the package code (it's been a while) and I think we have a similar issue to this for [`editFeatures`](https://github.com/r-spatial/mapedit/blob/master/R/edit.R#L263). I will investigate shortly. 

Likely not for the next CRAN release of **mapedit** but I will also investigate whether it makes sense to export `initMap` from **mapview**.  I don't quite like the code duplication as a long-term solution (I have similar issues throughout other packages).
