### ISSUE TITLE
Strange case of difficult viewing

### ISSUE THREAD

**Issue by agronomofiorentini** [r-spatial/mapedit#118]
Good evening
First of all, I am a great fan of this package because it speeds up my work like crazy.

I am using the mapedit module for shiny to allow the user to report the contours of farm plots.

The strange thing is that when i use:
1. The shiny viewer
2. The localhost 
3. Mobile phone

The map it works perfectly correctly. 

While when I use some computers (windows 10 + chrome) I report some display errors.

Can you help me to understand what is the mystery?

Thank you
![Screenshot_4](https://user-images.githubusercontent.com/66969646/132257462-4d15f956-9722-49d0-9dfc-6a32d478fc98.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/66969646/132257465-70d6943e-77b3-4113-b739-0bf4621e6702.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/66969646/132257475-6d96f839-44ee-471b-b96e-0ed1208db7a1.jpg)

**Comment by timelyportfolio** [comment]
@agronomofiorentini glad you are enjoying `mapedit`.  Since I don't have a replicable example, would you be able to confirm if you have the same result when only using `leaflet` not wrapped with `mapedit`?  This likely means that the map is not showing because of a transition or no size on first render.  Let me know and we can try to debug.

**Comment by agronomofiorentini** [comment]
Hi @timelyportfolio based on your suggestion i have developed the same application but in this case i used just leaflet without editmod module from the mapedit package

By using the follow code but the problem persist.
Viewer pane rstudio; localhost and mobile phone it is working perfectly while on the chrome browers in windows doesn't work

You can check the problem in this url
https://automaticfarmsolution.shinyapps.io/ReportSatellite_2/

UI - Component
leafletoutput("map")

Server - Component
output$map<-renderLeaflet({
leaflet() %>%
        
        addProviderTiles(providers$OpenStreetMap,
                         options = tileOptions(minZoom = 2, maxZoom = 15)) %>%
        
        addProviderTiles(providers$Esri.WorldImagery,
                         options = tileOptions(minZoom = 15, maxZoom = 20),
                         group = "Esri.WorldImagery") %>%
        
        addControlGPS(options = gpsOptions(position = "topleft",
                                           activate = TRUE,
                                           autoCenter = TRUE,
                                           maxZoom = 5,
                                           setView = TRUE)) %>%
        
        leaflet.extras::addSearchOSM(options = searchOptions(collapsed = TRUE, autoCollapse = TRUE)) %>%
        
        addDrawToolbar(targetGroup='drawPoly',
                       polylineOptions = F,
                       circleOptions = F,
                       markerOptions = F,
                       circleMarkerOptions = F,
                       rectangleOptions = F,
                       singleFeature = FALSE,
                       editOptions = editToolbarOptions(selectedPathOptions = selectedPathOptions())) %>%
        
        addMeasure(primaryLengthUnit = "meters",
                   primaryAreaUnit = "hectares",
                   position = "topleft",
                   activeColor = "red",
                   completedColor = "red",
                   localization = "it")
})

**Comment by agronomofiorentini** [comment]
I honestly don't know.

I updated both mapview, leaflet, shiny and then strangely enough it fixed the problem.

but the problem originally was that both locally and in the shiny viewer and mobile phone it displayed the map perfectly.

Instead when you proceeded to develop in shinyapps.io and use a microsoft device + chrome browser the map did not render.

**Comment by tim-salabim** [comment]
Ok, maybe they updated shinyapp.io lately... Who knows. I'll close here
