### ISSUE TITLE
Coordinates using editMap() with addRasterRGB() are wrong

### ISSUE THREAD

**Issue by TiagoOlivoto** [r-spatial/mapedit#130]
Hi! 
Thanks for developing such an useful tool!

I have noticed a strange issue while using editMap() and addRasterRGB(). You can try the following by drawing a polygon in any area of the raster 'rgb'

```
require(raster)
require(stars)
require(plainview)
require(leaflet)
library(leafem)
library(sf)
rgb <- plainview::poppendorf
```

# works fine (using addGeoRaster())
```
res <- 
leaflet() %>%
  addTiles(group = "OpenStreetMap") %>%
  addGeoRaster(rgb) |> 
  editMap()
  
polygons_spv <- sf::st_transform(res$finished$geometry, crs = sf::st_crs(rgb))

plot(rgb[[1]])
lines(as.matrix(polygons_spv[[1]]))
```

# wrong coordinates when using addRasterRGB()
```
res <- 
  leaflet() %>%
  addTiles(group = "OpenStreetMap") %>%
  addRasterRGB(rgb, 4,3,2, group = "True colours") |>
  editMap()

polygons_spv <- sf::st_transform(res$finished$geometry, crs = sf::st_crs(rgb))

plot(rgb[[1]])
lines(as.matrix(polygons_spv[[1]]))
```

This make to me extract the pixels from the wrong location when using editMap() to create polygons in the image. 
Can you please help with this?
Thanks

**Comment by tim-salabim** [comment]
Hm, I can't seem to reproduce this... Can you post some of the resulting plots? And could you give us your `sessionInfo()`?

**Comment by TiagoOlivoto** [comment]
Thanks for the prompt response!

Just to keep you up to date. I use editMap() in my package pliman to analyze orthomosaics. Generally, I need high zoom levels (~ 0.2 m) to select the cropping area correctly.

When using addGeoRaster(), the coordinates seems to be correct

**Packages and raster image**

```
library(mapedit)
require(plainview)
require(leaflet)
library(leafem)
library(sf)
library(terra)
library(stars)
rgb <- terra::rast(plainview::poppendorf)
```

**works fine (using addGeoRaster())**

```
res <- 
  leaflet() %>%
  addTiles(group = "OpenStreetMap") %>%
  addGeoRaster(rgb |> st_as_stars()) |> 
  addMouseCoordinates() |> 
  editMap(editor = "leafpm")

# crop the raster and show the draw rectangle
polyn <- res$finished$geometry
polygons_spv <- sf::st_transform(polyn, crs = sf::st_crs(rgb))
polygons_ext <- terra::vect(polygons_spv)
ext <- terra::buffer(polygons_ext, 100) |> terra::ext()
rgb_cr <- terra::crop(rgb, ext)
plot(rgb_cr[[1]])
lines(as.matrix(polygons_spv[[1]]))

```

![image](https://github.com/r-spatial/mapedit/assets/34458429/9499897e-947d-4e14-87c1-f7ac65ae5f0c)



**wrong coordinates when using addRasterRGB()**
Using the addRasterRGB, I can see that the draw rectangle in the cropped raster is not in the same position as I observed when editing. After a detailed look, I noticed that the coordinates shown in the viewer are not the same for the same pixel compared to addGeoRaster(). Maybe a bug with addRasterRGB()?

```
res <- 
  leaflet() %>%
  addTiles(group = "OpenStreetMap") %>%
  addRasterRGB(rgb |> st_as_stars()) |> 
  addMouseCoordinates() |> 
  editMap(editor = "leafpm")

polyn <- res$finished$geometry
polygons_spv <- sf::st_transform(polyn, crs = sf::st_crs(rgb))
polygons_ext <- terra::vect(polygons_spv)
ext <- terra::buffer(polygons_ext, 100) |> terra::ext()
rgb_cr <- terra::crop(rgb, ext)
plot(rgb_cr[[1]])
lines(as.matrix(polygons_spv[[1]]))
```

![image](https://github.com/r-spatial/mapedit/assets/34458429/217429ce-8065-4edf-99b7-e7f0d5a776be)


Thanks in advance!

**Comment by TiagoOlivoto** [comment]
I fixed this issue by using viewRGB() within pliman. So, I believe I can now close this.
