### ISSUE TITLE
leaflet.extras?

### ISSUE THREAD

**Issue by restonslacker** [r-spatial/mapedit#16]
Where does one obtain `leaflet.extras`? it does not seem to be available from CRAN:
```
> "leaflet.extras" %in% rownames(available.packages())
[1] FALSE
```

**Comment by tim-salabim** [comment]
https://github.com/bhaskarvk/leaflet.extras, hence

 `devtools::install_github("bhaskarvk/leaflet.extras")`

**Comment by restonslacker** [comment]
Thanks!

**Comment by edzer** [comment]
I also committed that in the [blog](http://r-spatial.org/r/2017/01/30/mapedit_intro.html).

**Comment by restonslacker** [comment]
cool.  fwiw, as I put in #17, the cran version of `leaflet` is too old and so the GH version is required as well.
