### ISSUE TITLE
camelCase for consistency

### ISSUE THREAD

**Issue by timelyportfolio** [r-spatial/mapedit#20]
@tim-salabim brings up a good point that `leaflet` and `mapview` are camelCase.  `sf` though is snake_case.   Since `leaflet` and `mapview` are closest, I think that we should switch to camelCase.   We are early enough in development that we can and should decide definitively at this point to prevent pain of a major API change.  Thoughts?

**Comment by timelyportfolio** [comment]
@tim-salabim,  can we push forward with this?  If you plan to demo at useR, I would like to have the correct API in place to prevent further disruption :)

**Comment by tim-salabim** [comment]
Yes, we can :-)

**Comment by timelyportfolio** [comment]
@tim-salabim want to push the button on #22 or me ? :)

![image](https://cloud.githubusercontent.com/assets/837910/26460827/92fd9aec-4140-11e7-812d-9afdbd9320f5.png)

**Comment by timelyportfolio** [comment]
Also, once accepted, I changed the blog post and examples to reflect API change.  How is best to get the updated post on r-spatial.org?

**Comment by edzer** [comment]
A PR!

**Comment by tim-salabim** [comment]
@timelyportfolio push the button. I won't have access to a computer until tomorrow night...

**Comment by timelyportfolio** [comment]
done, I will leave the issue open, so I don't forget to update all references in issues, examples, and posts

**Comment by timelyportfolio** [comment]
I think this is all done, so closing.  Please let me know if there is any reason to reopen.
