### ISSUE TITLE
edit and select as modules

### ISSUE THREAD

**Issue by timelyportfolio** [r-spatial/mapedit#21]
In the first release, we chose to return the values from `edit` and `select` to the R console.  However, for greater impact, providing a Shiny module will allow users to easily add `edit` and `select` within a larger Shiny app.  I'd like to add functions for the modules and then change `edit` and `select` to use the modules.  To prevent confusion, `edit` and `select` should probably still be used to return values to R.

**Comment by tim-salabim** [comment]
Fully agreed, there are more questions on SO re leaflet within shiny than re leaflet alone and I assume this may well be the case for mapedit too

**Comment by timelyportfolio** [comment]
I will wait for confirmation on #22 before moving on to the module pattern.

**Comment by timelyportfolio** [comment]
I have started working toward the goal of modules in https://github.com/timelyportfolio/mapedit/tree/modules since I can see that this feature might be very useful.  If any brave soul wants to try it out in its infancy,

```
devtools::install_github("timelyportfolio/mapedit@modules")
```

Then run any of the `selectMap` examples, or to see in Shiny context, check out https://github.com/timelyportfolio/mapedit/blob/modules/inst/experiments/shiny_modules.R.  **Please note this uses new camelCase**

**Comment by timelyportfolio** [comment]
Just tweeted this screenshot of using the new edit Shiny module for intersect/select.

![mapedit_module](https://cloud.githubusercontent.com/assets/837910/26640799/60666eee-45ee-11e7-8bbd-33d45656aeb3.gif)

**Comment by tim-salabim** [comment]
cool!

**Comment by timelyportfolio** [comment]
With `0.2.0` I think modules are added and working as expected.  Will document in next post and add full roxygen.  Please reopen if there are problems.
