### ISSUE TITLE
easy selectMap for simple features sf

### ISSUE THREAD

**Issue by timelyportfolio** [r-spatial/mapedit#24]
This is a promotion of the discussion in #19 with particular reference to comments.

- https://github.com/r-spatial/mapedit/issues/19#issuecomment-301438747
- https://github.com/r-spatial/mapedit/issues/19#issuecomment-301448497
- https://github.com/r-spatial/mapedit/issues/19#issuecomment-301608803
- https://github.com/r-spatial/mapedit/issues/19#issuecomment-304647791

<hr/>

@fdetsch proposed the idea of providing a `selectMap` wrapper for `sf` and @tim-salabim responded with `selectFeatures`.  This seemed to work well until the `selectFeatures` was integrated into the `MODIS` package https://github.com/MatMatt/MODIS/commit/353c2f4692279191135426e9cdad8838a440a880.  `selectFeatures` then erratically returned the selection, and I have replicated on my machine.

**Comment by timelyportfolio** [comment]
I first thought that the bug might be caused by wrapping a Shiny gadget in a function, but I cannot replicate when doing this, so failure 1 on correcting.

```
library(mapview)
library(leaflet)
library(shiny)
library(mapedit)

sf_select <- function(xsf) {selectFeatures(xsf)}
#bsf <- sf_select(breweries91)

library(sf)
library(MODIS)
shp <- system.file("external", "modis_latlonWGS84_grid_world.shp", package = "MODIS")
grd <- st_read(shp)
gsf <- sf_select(grd)
plot(gsf)
```

but there might be a clue in this failure.  If we uncomment the `bsf <- ...` line, the Shiny gadget only runs once when run inline.

**Comment by timelyportfolio** [comment]
@tim-salabim, should we use S3 and change `selectFeatures()`  to `selectMap.sf()`?  With resolution of https://github.com/r-spatial/mapview/issues/85, will this become even easier?

**Comment by tim-salabim** [comment]
I am not sure. I feel that `selectFeatures` is more instructive as the intention is to select features not a map. Wouldn't it make sense to have `selectMap` for map objects (leaflet, mapview) and `selectFeatures` for spatial objects (sf, sp, ...)?

**Comment by timelyportfolio** [comment]
@fdetsch, as I look more deeply into the riddle of erratic return, I am even more confused since

```
x <- MODIS:::mapSelect()
str(x)
```

works without issue every time for me.  I wonder if the error might be caused by some logic in `getTile()`, or if perhaps nesting the functions is the source of the trouble.  I will keep researching.

**Comment by timelyportfolio** [comment]
I am starting to suspect `dialogViewer` as the potential source of our trouble.  In my `modules` branch https://github.com/timelyportfolio/mapedit/commit/b6f0c17884c83eeb0c4cc518db7255cb11a68251, I changed to use the default `paneViewer` instead of `dialogViewer`.  After this change, I can no longer replicate the erratic `getTile()`.

```
# devtools::install_github("timelyportfolio/mapedit@modules")

library(MODIS)
library(leaflet)
library(mapedit)

lapply(1:3, function(x) getTile())
```

**Comment by timelyportfolio** [comment]
@tim-salabim, if this is the "solution", it will mean we will not be able to use the separate dialog popup.  Instead, we will have to use the viewer pane or default browser.  Is this acceptable?

**Comment by tim-salabim** [comment]
@timelyportfolio this is acceptable. I agree that having a `viewer` argument would be good so we can control default (pane?) but user can choose to their liking.
I just had a play around and am very impressed! Even things like this work nicely:
```r
leaflet() %>% 
  addTiles() %>% 
  addFeatures((sel <<- selectFeatures(franconia)), 
              popup = popupTable(sel)) %>% 
  addMouseCoordinates() %>%
  addLogo("https://avatars1.githubusercontent.com/u/837910?v=3&s=460")
```
I think this is nice as it enables people to flexibly set up their workflow.

**Comment by tim-salabim** [comment]
@timelyportfolio is it possible to make the map element in the viewer pane automatically resize to the available space?

**Comment by timelyportfolio** [comment]
Yes I think so but will verify this afternoon.

**Comment by timelyportfolio** [comment]
I thought I had figured this out at one point, but `height="auto"` and `height="100%" both result in blank screens.  Unfortunately, while `width="100%` or `width="auto"` work as expected, we cannot do the same with `height`.  I will try a different approach :(

**Comment by fdetsch** [comment]
Sorry for the late reply, guys. German public holidays and stuff...  

@timelyportfolio, after adding some missing `leaflet::` assignments to R/modules.R (see pull request [https://github.com/r-spatial/mapedit/pull/28](https://github.com/r-spatial/mapedit/pull/28)), interactive tile selection through `MODIS::getTile()` seems to work permanently. Thanks for the great work!

**Comment by timelyportfolio** [comment]
I think we can close this.  If anybody sees any issues, please reopen.  Thanks all!

**Comment by tim-salabim** [comment]
@timelyportfolio any news on the issue of making the map element fit the available space in the paneViewer?

**Comment by timelyportfolio** [comment]
Will resume work on filling `height` and so that I don't forget again, file a new issue focused on this behavior.
