### ISSUE TITLE
select abstraction

### ISSUE THREAD

**Issue by mdsumner** [r-spatial/mapedit#27]
I haven't explored the implications of this enough, but I definitely see the need to have a lower level function than selectFeatures.sf to pass back an index from a select operation. 

We could do `selectFeatures(x)$column` but that seems a bit round-about.  I'll want to use this to classify data values in the data.frame, so you might do something like this: 

```
x %>% mutate(selected = selectFeaturesIndex(x)) %>% filter(selected & property > value) 
```
(I presume it probably doesn't actually make sense to include the out select logic in the pipe like this, it's probably too much to ask to get `mutate(selected = selectFeatures(.))` to work this way. )

More straightforward would be

```
x$selected <- selectFeaturesIndex(x)
x %>% filter(selected & property > value) 
```

`selectFeaturesIndex` would add layer of abstraction, return a logical vector and be used by `selectFeatures`, and other filter+other functions we could write.   

Apologies for not actually having tried this out, but wanted to ask about it sooner rather than later.

**Comment by timelyportfolio** [comment]
With recent changes in my `@modules` branch of `mapedit` and `mapview::addFeatures()`, we can get much closer to your outcome.  Here is a quick example.  I know it is not exactly what you are asking, so I will think through a better implementation.

```
library(mapedit)
library(mapview)
library(sf)

fr_sf <- st_as_sf(franconia)

selectMap(
  leaflet() %>% addFeatures(data=fr_sf, layerId=~seq_len(nrow(fr_sf)))
)
```

**Comment by tim-salabim** [comment]
@timelyportfolio just as a side-note, there is no need for `st_as_sf(franconia)`, it already is `sf`

**Comment by timelyportfolio** [comment]
thanks @tim-salabim I forgot :)

@mdsumner, with https://github.com/timelyportfolio/mapedit/commit/8f7b04ff1fc5325ea2f74adfd9a67c4a6a6926e0 there is now an `index` argument to `selectFeatures`.  Please let me know if this accomplishes your objective and any feedback you might have.

```
# devtools::install_github("r-spatial/mapview@develop")
# devtools::install_github("timelyportfolio/mapview@modules")
library(mapview)
library(mapedit)

selectFeatures(franconia, index=TRUE)
```

**Comment by mdsumner** [comment]
Thanks!

**Comment by timelyportfolio** [comment]
Will close, since it seems this is mostly solved.  Let me know if I am missing something and will happily reopen and address.
