### ISSUE TITLE
editing or removing polygons with holes

### ISSUE THREAD

**Issue by timelyportfolio** [r-spatial/mapedit#32]
promoting https://github.com/r-spatial/mapedit/issues/29#issuecomment-309239108 to a separate issue as hole editing and removal could be a very nice use case for `mapedit`

<hr/>

Based on the original issue comment, there seems to be a bug with hole editing that I have not been able to reproduce yet.  Beyond the bug, hole editing and removal would be a nice feature.  There was some discussion on hole editing at https://github.com/Leaflet/Leaflet.draw/issues/90 and https://github.com/Leaflet/Leaflet.draw/pull/146, but this appears to have died.

**Comment by timelyportfolio** [comment]
@tim-salabim, I believe I have been able to reproduce the error from your example.  There seem to be two issues.  The first is merging with `tibble`-based `sf`, which I will fix as quickly as possible.  The second is editing any polygon with holes; without https://github.com/Leaflet/Leaflet.draw/pull/146 I am not sure we can correct this problem.

**Comment by timelyportfolio** [comment]
#391 more thoroughly describes the `tibble` issue.  https://github.com/timelyportfolio/mapedit/commit/df77aaf999e9e4188dc41b2edd333b76c5a154ce resolves the issue.

**Comment by tim-salabim** [comment]
Partially cross-posting from #29:

I noticed that hole vertices become un-editable when you move the enclosing polygon. Also, deleting hole vertices is a final deletion, i.e. it doesn't seem to respect pressing cancel to undo stuff. In any case, I think this is all not our problem at this point as this all stems from the `Leaflet.Draw` plugin if I'm not mistaken.

**Comment by timelyportfolio** [comment]
@tim-salabim, your statement is correct.  I will leave this open though as a reminder to check back on `Leaflet.draw` pull and also explore other potential plugins.

**Comment by timelyportfolio** [comment]
I believe we can safely close this now with the addition of `leafpm`. Please reopen if we should continue the discussion.
