### ISSUE TITLE
editFeatures of only one point zooms in to zoom level 100

### ISSUE THREAD

**Issue by tim-salabim** [r-spatial/mapedit#35]
`editFeatures(breweries[1, ])` will zoom in to a zoom level of 100 in the initial view. This is, I assume, because zoom level 100 is the maxZoom defined in mapview (to enable scrolling past the default zoom of 18/19 to investigate whether a line may actually be a polygon - useful for sliver polygons). I think we need to use leaflet's default `expandLimits` (or similar) to initiate the view.

**Comment by tim-salabim** [comment]
On further investigation I think this stems from [these lines](https://github.com/r-spatial/mapedit/blob/master/R/edit.R#L149-L155). We could leverage `mapview:::createExtent` (which is also used for setting the view of the homebutton. Thought this function could be enhanced a little as it zooms out too far at the moment for one point only. I will investigae in mapview....

**Comment by timelyportfolio** [comment]
Happy to work on this.  Just let me know.

**Comment by tim-salabim** [comment]
If you could that would be great.
I think this is two-fold. `mapview:::createExtent` is a mapview function that mostly behaves like the default leaflet initial view but ever so often (e.g. for single points) doesn't. If we could get this behaving similar to how leaflet determines the initial view for features that would be very beneficial for both mapview and mapedit.
Note though, that there are instances in mapview where we need `createExtent` to mimic exactly `st_bbox` or `raster::extent`, i.e. in `viewExtent`

**Comment by tim-salabim** [comment]
this should be fixed via 9f35a9ebf76d2064fd90ae62578a096a8359f723

**Comment by timelyportfolio** [comment]
Thanks!!!! Verified working on my end.
