### ISSUE TITLE
Display non-geographical maps ala leafletjs

### ISSUE THREAD

**Issue by vbonhomme** [r-spatial/mapedit#67]
Hi and thanks a lot for the awesome job here (and elsewhere).

I have no idea where to ask this question but I try here. Apologies if I should ask to `leaflet` for R or elsewhere.

I have struggling hard and for long to develop a digitizing software for morphometrics. Long story short: it would be widely used _and_ mapview/edit are more than starters.

One blocking aspect for this now is to properly display images using pixels coordinates. So far, I manage to display any image using `raster` with `xmx`= 1 (and the ratio for `ymx`) but that's far from being clean (ie we need to retransform into pixels, scales are wrong, etc.).

I would pretty much need what's described in the [leafletjs doc](http://leafletjs.com/examples/crs-simple/crs-simple.html) for non-geographical maps. On the `leaflet()` side, `L.CRS.Simple` seems to be the way to go, but, for such raster, we still need a projection. I have tried for a week and I nearly #made no progress. So, dear gurus, any idea how can we circumvent this problem and project an image (as a raster) in pixels coordinates and on a cartesian plan? A reproducible and minimal bit of code below if this may help.

Thanks a lot for your time and skills

````
# dependencies
library(jpeg)
library(raster)
library(leaflet)
library(leaflet.extras)
library(mapview)
library(mapedit)

# dl an image
path <- "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/CheHigh.jpg/280px-CheHigh.jpg"
che <- tempfile()
download.file(path, che, mode="wb")
im <- jpeg::readJPEG(che)

# prepare a raster from it
r  <- raster(xmn=0, xmx=1,
             ymn=0, ymx=nrow(im)/ncol(im),
             ncols=ncol(im), nrows=nrow(im))
r <- setValues(r, as.numeric(t(im)))

# prepare the leaflet
lf <- leaflet() %>% addTiles() %>% addRasterImage(r)
# view it
editMap(lf)
````

**Comment by vbonhomme** [comment]
also ask the question in SO, [there](https://stackoverflow.com/questions/47788171/display-non-geographical-maps-using-r-leaflet-shiny)

**Comment by tim-salabim** [comment]
See also these two threads

https://github.com/rstudio/leaflet/issues/371
https://github.com/r-spatial/mapedit/issues/54

leaflet currently does not render raster images with arbitrary or no crs. In an early version of mapview we circumvented this with the approach you mention via scaling the coordinates to lie between 0 and 1. However, I agree that this is not a solution, especially for digitizing.
One hope I have is that whenever leaflet gets updated to leafletjs 1.x this issue will be resolved. @timelyportfolio have you ever tested whether rasters work with `L.CRS.Simple` in the leaflet 1.x branch?

**Comment by vbonhomme** [comment]
Hi @tim-salabim  and @timelyportfolio (me again!)

With mapview(r, native.crs=TRUE) I got the (seen-elsewhere) following error:

```
Error in round(size) : non-numeric argument to mathematical function
In addition: Warning message:
In rasterCheckSize(x, maxpixels = maxpixels) :
  maximum number of pixels for Raster* viewing is #BEBEBE80 ; 
the supplied Raster* has 100520 
 ... decreasing Raster* resolution to #BEBEBE80 pixels
 to view full resolution set 'maxpixels =  100520 '
```

`plainview(r)`works though and if we could do the same things that we do with a regular `editmap` I think the main problem would be solved!

**Comment by tim-salabim** [comment]
This has been fixed recently, see https://github.com/r-spatial/mapview/issues/111
So if you install mapview from github you should be able to use `native.crs = TRUE`

**Comment by vbonhomme** [comment]
indeed!

**Comment by vbonhomme** [comment]
@timelyportfolio may I ping you to have your feeling about what @tim-salabim suggested? Cheers!

**Comment by timelyportfolio** [comment]
Sure, feel free to ping me.  Might be a little slower in responding over the holidays.  Cheers!

**Comment by vbonhomme** [comment]
@timelyportfolio , that was a question, perhaps too politely asked ;-)

**Comment by timelyportfolio** [comment]
Ok, I understand now.  I very likely am headed down the wrong path, so feel free to set me straight.

1.  `addRasterImage()` creates a tile layer.  Is this necessary, or is the `L.imageOverlay` as in [example](http://kempe.net/blog/2014/06/14/leaflet-pan-zoom-image.html) sufficient?

2.  This might be helpful down the road https://github.com/Leaflet/Leaflet.draw/issues/611.

Some code as a demonstration of the very little that I accomplished.

```
library(jpeg)
library(raster)
library(leaflet)
library(leaflet.extras)
library(mapview)
library(mapedit)

# dl an image
path <- "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/CheHigh.jpg/280px-CheHigh.jpg"
che <- tempfile()
download.file(path, che, mode="wb")
im <- jpeg::readJPEG(che)

# prepare a raster from it
r  <- raster(xmn=0, xmx=1,
             ymn=0, ymx=nrow(im)/ncol(im),
             ncols=ncol(im), nrows=nrow(im))
r <- setValues(r, as.numeric(t(im)))

# prepare the leaflet
lf <- leaflet(
  options = leafletOptions(
    crs = leafletCRS("L.CRS.Simple"),
    minZoom = 1,
    maxZoom = 10
  )
) %>%
  setView(0, 0, zoom=3)

lf2 <- htmlwidgets::onRender(
  lf,
sprintf(
"
  function(el, x) {
    var map = this;
    var w = %s,
        h = %s,
        url = 'http://upload.wikimedia.org/wikipedia/commons/thumb/5/58/CheHigh.jpg/280px-CheHigh.jpg';
    
    // calculate the edges of the image, in coordinate space
    var southWest = map.unproject([0, h], 3);
    var northEast = map.unproject([w, 0], 3);
    var bounds = new L.LatLngBounds(southWest, northEast);

    L.imageOverlay(url, bounds).addTo(map);
  }
",
  dim(im)[2],
  dim(im)[1]
)
)

editMap(lf2)
```

`leaflet.extras` uses `layer.toGeoJSON()` which does not give pixel coordinates unfortunately (or at least I think unfortunately).

I know this isn't much, but maybe it will get me one step further towards something usable.

**Comment by vbonhomme** [comment]
Thanks a lot, that unlocks some key aspect of my problem ! I'll dig it further and let you know.
