### ISSUE TITLE
editMap: no method 'st_read' for object of classe "json"

### ISSUE THREAD

**Issue by statnmap** [r-spatial/mapedit#68]
I have an issue using {mapedit} with the github dev version of {sf}.
I use that:
```
library(mapview)
library(mapedit)

what_we_created <- mapview() %>%
  editMap()
```
But when I clicked on "Done", I have the following error:
> no method 'st_read' for object of classe "json"

The console also shows the following steps:
```
Listening on http://127.0.0.1:4217
Warning: Error in UseMethod: pas de méthode pour 'st_read' applicable pour un objet de classe "json"
Stack trace (innermost first):
    91: st_read
    90: as.data.frame
    89: tibble::as_tibble
    88: st_as_sf
    87: sf::read_sf
    86: st_as_sfc.geo_list
    85: FUN
    84: lapply
    83: combine_list_of_sf
    82: FUN
    81: lapply
    80: <reactive>
    69: crud
    68: observerFunc
    13: shiny::runApp
    12: shiny::runGadget
    11: editMap.leaflet
    10: editMap.mapview
     9: editMap
     8: function_list[[k]]
     7: withVisible
     6: freduce
     5: _fseq
     4: eval
     3: eval
     2: withVisible
     1: %>%
```

This works correctly with the CRAN version of library {sf}, so it seems that something has changed in the {sf} objects format, which has not been taken into account in {mapedit}. This does not work with dev version of {mapedit} too.

**Comment by timelyportfolio** [comment]
Thanks so much for the report.  Because of holidays response unfortunately will be slower than normal.  I hope to resolve before end of next week.

**Comment by tim-salabim** [comment]
Thanks @edzer
