### ISSUE TITLE
Please explain in tutorial how to convert to sp object, spatial, or geojson (for conversion to shapefile/s). 

### ISSUE THREAD

**Issue by ZOMBIEKING907** [r-spatial/mapedit#70]
Thanks for making this project.  I would like to use if for some GIS projects I have but I'm having trouble converting the object made by editMap to something I could use writeOGR with.  

It might be elementary to you but it would be helpful for myself. Thanks!

**Comment by edzer** [comment]
have you tried `as(obj, "Spatial")`?

**Comment by timelyportfolio** [comment]
Thanks @edzer!  @ZOMBIEKING907, please let us know if this fulfills your request.

**Comment by timelyportfolio** [comment]
I am going to close due to lack of response.  Please reopen if the issue has not been resolved.
