### ISSUE TITLE
new mapview::addImageQuery breaks editMap

### ISSUE THREAD

**Issue by tim-salabim** [r-spatial/mapedit#74]
While introducing `drawFeatures` I noticed that the newly introduced `mapview::addImageQuery` (which is used by default in mapview for raster layers) breaks `editMap`.

```r
library(mapedit)
library(mapview)
library(leaflet)

m_leaf_wo = leaflet() %>%
  addProviderTiles("OpenStreetMap") %>%
  addRasterImage(poppendorf[[4]], layerId = "rst")

m_leaf_w = leaflet() %>%
  addProviderTiles("OpenStreetMap") %>%
  addRasterImage(poppendorf[[4]], layerId = "rst") %>%
  addImageQuery(poppendorf[[4]], layerId = "rst")

m_mapv_wo = mapview(poppendorf[[4]], label = FALSE)

m_mapv_w = mapview(poppendorf[[4]])

editMap(m_leaf_wo) # works fine
editMap(m_leaf_w)  # doesn't work
editMap(m_mapv_wo) # works fine
editMap(m_mapv_w)  # doesn't work
```
Alone, all these maps work fine and the `imageQuery` is displayed as intended.

@timelyportfolio I see lots of shiny related js stuff when inspecting in the browser console so my hunch is that `mapview::adImageQuery` lacks shiny support somehow. Yet, my knowledge of both shiny and js is too limited to understand what's going on. The relevant js code for `addImageQuery` is found [here](https://github.com/r-spatial/mapview/tree/develop/inst/htmlwidgets/lib/joda). Would you mind having a look at what's happening here and how to potentially fix it?

**Comment by timelyportfolio** [comment]
@tim-salabim good catch.  I did not think to test `mapview::addImageQuery`.  I will take a look to assess what might be happening.

**Comment by timelyportfolio** [comment]
@tim-salabim thinking further, what Shiny functionality might we want to add to `addImageQuery` in `mapedit`? Perhaps, we should discuss this over in `mapedit`, but while I am digging into the code, I thought it might be good to keep in mind.

**Comment by tim-salabim** [comment]
@timelyportfolio mentioning shiny here was just my ignorance of what may cause the shiny session in mapedit to break (it's not crashing - just not working properly). Honestly, I have no idea if and what is needed to make `addImageQuery` behave in a shiny session/mapedit. If so, the obvious place to discuss would be in mapview repo.

**Comment by timelyportfolio** [comment]
@tim-salabim digging in; this one looks like it might be nasty :)

**Comment by timelyportfolio** [comment]
looks like this doesn't have anything to do with `mapedit`, so closing here.  Let's discuss at https://github.com/r-spatial/mapview/pull/133 or in an issue in `mapview`.
