### ISSUE TITLE
Getting mapedit to work with Shiny and leaflet

### ISSUE THREAD

**Issue by GreyMerchant** [r-spatial/mapedit#95]
Hi,

Thanks for this package. The project  looks amazing and will be a phenomenal help going forward. I am struggling a bit to get everything to work and I hope I may ask for help here. 

So I want to get this functionality directly in Shiny: 
`what_we_created <- mapview() %>%
  editMap()`

I essentially just want to be able to call up a leaflet map and allow a person to draw a spatial polygon and get the shiny application to save that information in the background. 

I am able to get the package to work with this code on my server bit of my R code:

`shinyServer(function(input, output, session) {`
  `#callModule creates a small module`
 ` CM_edit <- callModule(editMod, "test-edit", m, record = TRUE)`
 `output$edited <- renderLeaflet({`
 `   req(CM_edit()$finished)`
`    mapview(CM_edit()$finished)@map`
`  })`
`  })`

However it is not the same as editMap() where you can hit "done" and get it to write to a df (I am also not sure if I am doing it entirely correct above). Is there some way to have this exact functionality in shiny?  

Any other help and tips would be appreciated! I am finding the syntax a bit strange still.

**Comment by timelyportfolio** [comment]
@GreyMerchant thanks so much for the issue.  There are different opinions on whether a question like this belongs in Github issues, but for `mapedit` Github issues is the encouraged forum.  I'm travelling currently, but I'll try to post an example once I get back fully online.  Glad you are using `mapedit`!

**Comment by mrjoh3** [comment]
Hi @GreyMerchant I hope this is what you are talking about. Below is my minimum example of using mapedit and leaflet with a button to save edits. In this case the button will also save the created spatial dataframe to a geojson file.

```


library(shiny)
library(leaflet)
library(mapedit)
library(sf)

map <- leaflet() %>%
    addTiles()



ui <- fluidPage(

    # Application title
    titlePanel("Minimal Shiny Leaflet Mapedit"),

    # Sidebar with a ui for grabbing mapedit data
    sidebarLayout(
        sidebarPanel(
            actionButton('save', 'Save from Map')
        ),

        # add map
        mainPanel(
            editModUI("map")
        )
    )
)


server <- function(input, output) {

    edits <- callModule(
        editMod,
        leafmap = map,
        id = "map"
    )
    
    observeEvent(input$save, {
        
        geom <- edits()$finished
        
        if (!is.null(geom)) {
            assign('new_geom', geom, envir = .GlobalEnv)
            sf::write_sf(geom, 'new_geom.geojson', delete_layer = TRUE, delete_dsn = TRUE)
        }
        
    })
}

# Run the application 
shinyApp(ui = ui, server = server)


```

**Comment by mrjoh3** [comment]
if you also wanted to manipulate the leaflet map you can use `leafletProxy` in the normal way. For example:

```
        leafletProxy("map-map") %>%
            addPolygons(data = geom, color = 'red')

```
notice the `map-map` reference? this is due the the module name spacing, so you could use `ns()` to make this more dynamic.

**Comment by GreyMerchant** [comment]
Thank you for the responses :) This reads far easier than the code I was looking at. Thank you so much!

**Comment by timelyportfolio** [comment]
going to close... please reopen if we missed anything.  Thanks for using `mapedit`.

**Comment by davis3tnpolitics** [comment]
@timelyportfolio or @mrjoh3 

Thank you both for taking time to help out people with this incredible package.

I'm working on integrating a leafletProxy into mapedit and I'm having an issue with re-rendering circle markers.

Working off one of the examples from issues, here's what's happening. I add the markers in the base map, make some edits to the map, do a little data manipulation in an observer, and then try to re-map the points with their new characteristics.

It runs perfectly until you hit refresh. At that point it just removes the markers and does not re-add the updated markers.

However, if you use the exact same code and enter lng= c(-84, -84.5) and lat= c(46,47), then it does add those circle markers. What's happening here? Any ideas? It doesn't throw any errors in R. But it does throw this in the console log:

leaflet.js:5 Deprecated use of _flat, please use L.LineUtil.isFlat instead.
Nt @ leaflet.js:5

`library(shiny)
library(leaflet)
library(leaflet.extras)
library(mapedit)
library(mapview)

ui <- tagList(
  editModUI("editor"),
  actionButton("refresh", "Refresh Points"),
)

server <- function(input, output, session) {
  # to use the namespace that we gave
  ns <- NS("editor")
  
  base_map <- leaflet(data= data) %>% 
    addTiles() %>% 
    addCircleMarkers(lng= data$lng, lat= data$lat)
  drawn <- callModule(editMod, "editor", base_map)

 leafletProxy(ns("map"))
  
  fin<- reactiveValues()
  observe({
    Some data manipulation here
    
    fin$data<- newdata
  })
  
  observeEvent(input$refresh, {
    leafletProxy(ns("map")) %>%
      clearMarkers()%>%
      addCircleMarkers(fin$data, lat= fin$data)
  })
  
}

shinyApp(ui, server)`

**Comment by davis3tnpolitics** [comment]
@timelyportfolio or @mrjoh3

Thank you both for taking time to help out people with this incredible package.

I'm working on integrating a leafletProxy into mapedit and I'm having an issue with re-rendering circle markers.

Working off one of the examples from issues, here's what's happening. I add the markers in the base map, make some edits to the map, do a little data manipulation in an observer, and then try to re-map the points with their new characteristics.

It runs perfectly until you hit refresh. At that point it just removes the markers and does not re-add the updated markers.

However, if you use the exact same code and enter lng= c(-84, -84.5) and lat= c(46,47), then it does add those circle markers. What's happening here? Any ideas? It doesn't throw any errors in R. But it does throw this in the console log:

leaflet.js:5 Deprecated use of _flat, please use L.LineUtil.isFlat instead.
Nt @ leaflet.js:5

library(shiny)
library(leaflet)
library(leaflet.extras)
library(mapedit)
library(mapview)

ui <- tagList(
editModUI("editor"),
actionButton("refresh", "Refresh Points"),
)

server <- function(input, output, session) {

#to use the namespace that we gave
ns <- NS("editor")

base_map <- leaflet(data= data) %>%
addTiles() %>%
addCircleMarkers(lng= data$lng, lat= data$lat)
drawn <- callModule(editMod, "editor", base_map)

leafletProxy(ns("map"))

fin<- reactiveValues()
observe({
Some data manipulation here

fin$data<- newdata
})

observeEvent(input$refresh, {
leafletProxy(ns("map")) %>%
clearMarkers()%>%
addCircleMarkers(fin$data, lat= fin$data)
})

}

shinyApp(ui, server)
